/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAL.Repositories;


import DAL.DataAccessObject;
import Domain.User;
import Domain.UserRole;
import Web.DTO.UserSessionDto;
import Web.SignUpServlet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Repository for users
 * @author azurwular
 */
public class UserRepository
{
    
    public boolean Exists(String email) throws SQLException
    {
        boolean result;
        
        // Query for the user
        PreparedStatement insertStatement;
        
        ResultSet rs;
        String insertSQL = "SELECT * from user where email = ?";

        Connection connection = DataAccessObject.getConnection();

        insertStatement = connection.prepareStatement(insertSQL);
        insertStatement.setString(1, email);

        rs = insertStatement.executeQuery();

        // If the user exists, there will be one result
        result = rs.next();

        DataAccessObject.releaseConnection(connection);

        return result;
    }
    
    /**
     * Gets user from database
     * @param email
     * @param password
     * @return
     * @throws SQLException
     * @throws NullPointerException 
     */
    
    public User Get(String email, String password) throws SQLException, NullPointerException, Exception 
    {
        // Hash the password
        String hashedSaltedPassword = PasswordUtils.getSaltedHash(password);
        
        // Query for the user
        PreparedStatement insertStatement;
        ResultSet rs;
        User user = null;
        String insertSQL = "SELECT * from user where email = ? AND password = ?";
        
        Connection connection = DataAccessObject.getConnection();
        
        insertStatement = connection.prepareStatement(insertSQL);
        insertStatement.setString(1, email);
        insertStatement.setString(2, hashedSaltedPassword);

        rs = insertStatement.executeQuery();

        if (rs.next())
        {
            String storedPasswordHash = rs.getString("password");
            if (!hashedSaltedPassword.equals(storedPasswordHash))
            {
                user = null;
            }
            else
            {
                user = new User(
                    rs.getInt("id"),
                    UserRole.valueOf(rs.getString("role")),
                    rs.getString("first_name"),
                    rs.getString("last_name"),
                    rs.getString("email"),
                    rs.getString("phone"),
                    rs.getString("address"),
                    rs.getString("zipcode"),
                    rs.getString("city"),
                    rs.getString("country"));
            }
        }
        
        DataAccessObject.releaseConnection(connection);
        
        return user;
    }
    
    //
    public int Create(User newUser) throws SQLException, Exception
    {
        // Hash password before storing
        String passwordHash = PasswordUtils.getSaltedHash(newUser.getPassword());
        
        PreparedStatement insertStatement;
        
        try
        {
            Connection connection = DataAccessObject.getConnection();
        
            // Execute insert
            String insertSQL = "insert into user(first_name, last_name, email, password, role) values(?,?,?,?,?)";
            insertStatement = connection.prepareStatement(insertSQL, Statement.RETURN_GENERATED_KEYS);
            insertStatement.setString(1, newUser.getFirstName());
            insertStatement.setString(2, newUser.getLastName());
            insertStatement.setString(3, newUser.getEmail());
            insertStatement.setString(4, passwordHash);
            insertStatement.setString(5, newUser.getRole().toString());

            insertStatement.executeUpdate();
            
            // Get autogenerated id of new user
            ResultSet rs = insertStatement.getGeneratedKeys();
            rs.next();
            int newUserId = rs.getInt(1);
            
            connection.close();
            
            return newUserId;
        }
        catch(SQLException ex)
        {
            Logger.getLogger(UserRepository.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }
    
    public void update (UserSessionDto user) throws SQLException
    {
        PreparedStatement insertStatement;
        
        try
        {
            Connection connection = DataAccessObject.getConnection();
        
            // Execute insert
            String insertSQL = "update user set first_name = ?, last_name = ?, email = ?, phone = ?, address = ?, zipcode = ?, "
                    + "city = ?, country = ? where id = ?)";
            insertStatement = connection.prepareStatement(insertSQL);
            insertStatement.setString(1, user.getFirstName());
            insertStatement.setString(2, user.getLastName());
            insertStatement.setString(3, user.getEmail());
            insertStatement.setString(4, user.getPhone());
            insertStatement.setString(5, user.getAddress());
            insertStatement.setString(6, user.getZipcode());
            insertStatement.setString(7, user.getCity());
            insertStatement.setString(8, user.getCountry());
            insertStatement.setInt(9,user.getId());
            

            insertStatement.executeUpdate();
            
            connection.close();
            
            
        }
        catch(SQLException ex)
        {
            Logger.getLogger(UserRepository.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
        
    }
    /*
    public Bottom getBottom (String bottom)
    {
        try {
            String query = "select name, price from bottoms where name = ?";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, bottom);
            
            ResultSet resultSet = preparedStatement.executeQuery();
            Bottom dbBottom;
            
            while(resultSet.next())
            {
                String name = resultSet.getString("name");
                double price = resultSet.getDouble("price");
                
                dbBottom = new Bottom(name, price);
                
                return dbBottom;
            }
        } catch (SQLException e) {
            System.out.println("Fail to query topping.");
            System.out.println(e.getMessage());
        }
        
        return null;
    }
    
    public Topping getTopping (String topping)
    {
        try {
            String query = "select name, price from topping where name = ?";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, topping);
            
            ResultSet resultSet = preparedStatement.executeQuery();
            Topping dbTopping;
            
            while(resultSet.next())
            {
                String name = resultSet.getString("name");
                double price = resultSet.getDouble("price");
                
                dbTopping = new Topping(name, price);
                
                return dbTopping;
            }
        } catch (SQLException e) {
            System.out.println("Fail to query topping.");
            System.out.println(e.getMessage());
        }
        
        return null;
    }
    
    public int createInvoice (Invoice invoice)
    {
        PreparedStatement insertStatement;
        try {
            String insertSQL = "insert into invoices(username) values(?)";
            insertStatement = con.prepareStatement(insertSQL);
            insertStatement.setString(1, invoice.getUsername());

            insertStatement.executeUpdate(insertSQL, 1);
            return insertStatement.getGeneratedKeys().getInt("id");
        } catch (SQLException e) {
            System.out.println("Fail in create new invoice. Check code");
            System.out.println(e.getMessage());
        }
        
        return -1;
    }
    
    public void addLineItems (ArrayList<LineItem> lineItems)
    {
        try {
            String insertSQL = "insert into lineitems(topping, bottom, quantity, username, invoiceId) values(?,?,?,?,?)";
            PreparedStatement insertStatement = con.prepareStatement(insertSQL);
            
            for(LineItem lineItem : lineItems)
            {
                insertStatement.setString(1, lineItem.getTopping().getName());
                insertStatement.setString(2, lineItem.getBottom().getName());
                insertStatement.setInt(3, lineItem.getQuantity());
                insertStatement.setString(4, lineItem.getUsername());
                insertStatement.setInt(5, lineItem.getInvoiceId());
                insertStatement.addBatch();
            }

            insertStatement.executeBatch();
            System.out.println("Line items created");
        } catch (SQLException e) {
            System.out.println("Fail in creating line items. Check code");
            System.out.println(e.getMessage());
        }
    }
*/
}
